<%
If Session("Status")<> "Econ333_01" Then
Response.Redirect("../../Login/login.asp")
Else
%>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=FrontPage.Editor.Document>
<meta name=Generator content="Microsoft FrontPage 4.0">
<link rel=File-List href="./Grades_files/filelist.xml">
<style id="Final_Grades2post_22676_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1522676
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl2422676
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Final_Grades2post_22676" align=center x:publishsource="Excel">

<table x:str border=1 cellpadding=0 cellspacing=0 width=570 style='border-collapse:
 collapse;table-layout:fixed;width:428pt'>
 <col width=81 style='mso-width-source:userset;mso-width-alt:2962;width:61pt'>
 <col width=60 style='mso-width-source:userset;mso-width-alt:2194;width:45pt'>
 <col width=61 style='mso-width-source:userset;mso-width-alt:2230;width:46pt'>
 <col width=71 style='mso-width-source:userset;mso-width-alt:2596;width:53pt'>
 <col width=69 style='mso-width-source:userset;mso-width-alt:2523;width:52pt'>
 <col width=64 style='width:48pt'>
 <col width=36 style='mso-width-source:userset;mso-width-alt:1316;width:27pt'>
 <col width=64 span=2 style='width:48pt'>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 width=81 style='height:12.75pt;width:61pt'><span
  style="mso-spacerun: yes"> </span>Student ID
    <p>(last 7 digits)</p>
  </td>
  <td class=xl2422676 width=60 style='border-left:none;width:45pt'>Partcipati<span
  style='display:none'>on</span></td>
  <td class=xl2422676 width=61 style='border-left:none;width:46pt'>Mid_Scor<span
  style='display:none'>e</span></td>
  <td class=xl2422676 width=71 style='border-left:none;width:53pt'>Fin_Quiz</td>
  <td class=xl2422676 width=69 style='border-left:none;width:52pt'>Fin_Essa1</td>
  <td class=xl2422676 width=64 style='border-left:none;width:48pt'>Fin_Total</td>
  <td class=xl2422676 width=36 style='border-left:none;width:27pt'>Paper</td>
  <td class=xl2422676 width=64 style='border-left:none;width:48pt'>Fin_Grade</td>
  <td class=xl2422676 width=64 style='border-left:none;width:48pt'>Letter Gra<span
  style='display:none'>de</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>357806</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>94</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>52</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>29</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D2+E2">81</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B2+0.35*C2+0.55*F2">87.45</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>524950</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9.5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>62</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>26</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>11</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D3+E3">37</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B3+0.35*C3+0.55*F3">51.55</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>898065</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>8</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>52</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>24</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D4+E4">76</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B4+0.35*C4+0.55*F4">77.8</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>357486</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>8.5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>90</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>42</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>21</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D5+E5">63</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B5+0.35*C5+0.55*F5">74.65</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>50825</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>67</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>44</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>17</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D6+E6">61</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B6+0.35*C6+0.55*F6">67</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>873957</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>8</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>82</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>21</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D7+E7">55</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B7+0.35*C7+0.55*F7">66.95</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>222412</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>4</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>63</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>42</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D8+E8">51</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B8+0.35*C8+0.55*F8">54.1</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>958459</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>98</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>46</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>35</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D9+E9">81</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B9+0.35*C9+0.55*F9">87.85</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>638199</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>94</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>25</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D10+E10">59</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B10+0.35*C10+0.55*F10">75.35</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>696434</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>98</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>42</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>23</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D11+E11">65</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>70</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B11+0.35*C11+0.35*F11+0.2*G11">76.05</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>908261</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>89</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>38</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>33</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D12+E12">71</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B12+0.35*C12+0.55*F12">75.2</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>909801</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>882099</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>182574</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>3</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>65</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>42</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>16</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D15+E15">58</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>70</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B15+0.35*C15+0.55*F15">60.05</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>93785</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>7</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>89</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>36</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>15</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D16+E16">51</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B16+0.35*C16+0.55*F16">66.2</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>696546</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>510030</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>8</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>40</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>16</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D18+E18">56</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B18+0.35*C18+0.55*F18">66.8</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>88856</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>5.5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>68</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>38</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>20</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D19+E19">58</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>77</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B19+0.35*C19+0.35*F19+0.2*G19">65</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>954721</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>4.5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>60</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>36</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>15</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D20+E20">51</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B20+0.35*C20+0.55*F20">53.55</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>718022</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>94</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>54</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>37</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D21+E21">91</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B21+0.35*C21+0.55*F21">91.95</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>792216</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>455588</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>91</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>42</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>27</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D23+E23">69</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B23+0.35*C23+0.55*F23">74.8</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>659649</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>3</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>74</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B24+0.35*C24+0.55*F24">28.9</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>F</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>946267</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>6</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>71</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>46</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>25</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D25+E25">71</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B25+0.35*C25+0.55*F25">69.9</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>973007</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>8</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>92</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>54</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>21</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D26+E26">75</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B26+0.35*C26+0.55*F26">81.45</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>984820</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>92</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>44</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D27+E27">78</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B27+0.35*C27+0.55*F27">85.1</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>43083</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9.5</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>30</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>32</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D28+E28">62</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B28+0.35*C28+0.55*F28">73.7</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2422676 align=right style='height:12.75pt;border-top:
  none' x:num>595621</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>9</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>77</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>28</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num>7</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=D29+E29">35</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2422676 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B29+0.35*C29+0.55*F29">55.2</td>
  <td class=xl2422676 style='border-top:none;border-left:none'>C</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=81 style='width:61pt'></td>
  <td width=60 style='width:45pt'></td>
  <td width=61 style='width:46pt'></td>
  <td width=71 style='width:53pt'></td>
  <td width=69 style='width:52pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=36 style='width:27pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
<% End if %>
