<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=FrontPage.Editor.Document>
<meta name=Generator content="Microsoft FrontPage 4.0">
<link rel=File-List href="./Grades.asp_files/filelist.xml">
<style id="Final_Grades2post_23276_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1523276
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl2423276
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Final_Grades2post_23276" align=center x:publishsource="Excel">

<table x:str border=1 cellpadding=0 cellspacing=0 width=566 style='border-collapse:
 collapse;table-layout:fixed;width:425pt'>
 <col width=137 style='mso-width-source:userset;mso-width-alt:5010;width:103pt'>
 <col width=103 style='mso-width-source:userset;mso-width-alt:3766;width:77pt'>
 <col width=90 style='mso-width-source:userset;mso-width-alt:3291;width:68pt'>
 <col width=84 style='mso-width-source:userset;mso-width-alt:3072;width:63pt'>
 <col width=88 style='mso-width-source:userset;mso-width-alt:3218;width:66pt'>
 <col width=64 style='width:48pt'>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 width=137 style='height:12.75pt;width:103pt'>ID#
  (last 7)</td>
  <td class=xl2423276 width=103 style='border-left:none;width:77pt'>Participation</td>
  <td class=xl2423276 width=90 style='border-left:none;width:68pt'>Mid-term_Scor<span
  style='display:none'>e</span></td>
  <td class=xl2423276 width=84 style='border-left:none;width:63pt'>Final_Score</td>
  <td class=xl2423276 width=88 style='border-left:none;width:66pt'>Final_Grade</td>
  <td class=xl2423276 width=64 style='border-left:none;width:48pt'>Letter Gra<span
  style='display:none'>de</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>639372</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>7.5</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>89</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>82</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B2+0.4*C2+0.5*D2">84.1</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>465177</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B3+0.4*C3+0.5*D3">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>743305</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B4+0.4*C4+0.5*D4">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>779509</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B5+0.4*C5+0.5*D5">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>197806</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="8.3333333333333339">8.333333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="85.733333333333334" x:fmla="=B6+0.4*C6+0.5*D6">85.73333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>722242</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="7.916666666666667">7.916666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>88</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="86.316666666666663" x:fmla="=B7+0.4*C7+0.5*D7">86.31666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>652765</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="8.0833333333333339">8.083333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>62</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>56</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="60.883333333333333" x:fmla="=B8+0.4*C8+0.5*D8">60.88333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>566041</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="3.3333333333333335">3.333333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>64</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>58</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="57.933333333333337" x:fmla="=B9+0.4*C9+0.5*D9">57.93333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>651594</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="4.166666666666667">4.166666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>76</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>70</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="69.566666666666663" x:fmla="=B10+0.4*C10+0.5*D10">69.56666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>930646</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>1</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>65</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>44</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B11+0.4*C11+0.5*D11">49</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>56260</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="1.6666666666666667">1.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>64</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="27.266666666666669" x:fmla="=B12+0.4*C12+0.5*D12">27.26666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>F</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>204505</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="0.83333333333333337">0.833333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>54</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="39.433333333333337" x:fmla="=B13+0.4*C13+0.5*D13">39.43333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>D</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>819766</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>6</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=54+6">60</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B14+0.4*C14+0.5*D14">70</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>928529</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>7.5</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=83+5">88</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>96</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B15+0.4*C15+0.5*D15">90.7</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>937079</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>100</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>96</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B16+0.4*C16+0.5*D16">98</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>811718</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>100</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>96</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B17+0.4*C17+0.5*D17">98</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>673353</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B18+0.4*C18+0.5*D18">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>948997</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.166666666666667">5.166666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>78</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>74</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="73.366666666666674" x:fmla="=B19+0.4*C19+0.5*D19">73.36666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>221122</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B20+0.4*C20+0.5*D20">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>953762</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="7.666666666666667">7.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>66</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="77.066666666666663" x:fmla="=B21+0.4*C21+0.5*D21">77.06666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>38256</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B22+0.4*C22+0.5*D22">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>671625</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.416666666666667">5.416666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>74</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="52.016666666666666" x:fmla="=B23+0.4*C23+0.5*D23">52.01666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>185554</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="9.1666666666666661">9.166666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>100</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="92.166666666666657" x:fmla="=B24+0.4*C24+0.5*D24">92.16666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>673512</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="8.3333333333333339">8.333333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>77</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>30</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="54.133333333333333" x:fmla="=B25+0.4*C25+0.5*D25">54.13333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>924962</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="1.6666666666666667">1.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>66</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="28.06666666666667" x:fmla="=B26+0.4*C26+0.5*D26">28.06666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>F</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>951857</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.166666666666667">5.166666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>64</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>62</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="61.766666666666666" x:fmla="=B27+0.4*C27+0.5*D27">61.76666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>694796</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.833333333333333">5.833333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>84</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="79.833333333333343" x:fmla="=B28+0.4*C28+0.5*D28">79.83333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>659382</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="3.3333333333333335">3.333333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>69</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>76</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="68.933333333333337" x:fmla="=B29+0.4*C29+0.5*D29">68.93333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>778556</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>70</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>68</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B30+0.4*C30+0.5*D30">62</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>C</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>453035</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B31+0.4*C31+0.5*D31">0</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>757847</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="1.6666666666666667">1.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>56</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>34</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="41.06666666666667" x:fmla="=B32+0.4*C32+0.5*D32">41.06666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>D</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>471124</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="6.666666666666667">6.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>72</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>72</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="71.466666666666669" x:fmla="=B33+0.4*C33+0.5*D33">71.46666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>806550</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>10</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>100</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>94</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B34+0.4*C34+0.5*D34">97</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>A</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>460</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="7.666666666666667">7.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>79</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>74</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="76.266666666666666" x:fmla="=B35+0.4*C35+0.5*D35">76.26666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>731212</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="3.6666666666666665">3.666666667</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>90</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="79.666666666666657" x:fmla="=B36+0.4*C36+0.5*D36">79.66666667</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>652648</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="9.5833333333333339">9.583333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>80</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>86</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="84.583333333333343" x:fmla="=B37+0.4*C37+0.5*D37">84.58333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 style='height:12.75pt;border-top:none'>&nbsp;</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>5</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>83</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>66</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num
  x:fmla="=B38+0.4*C38+0.5*D38">71.2</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>15160</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.833333333333333">5.833333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>92</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>74</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="79.63333333333334" x:fmla="=B39+0.4*C39+0.5*D39">79.63333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 align=right style='height:12.75pt;border-top:
  none' x:num>720088</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="5.833333333333333">5.833333333</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>90</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none' x:num>84</td>
  <td class=xl2423276 align=right style='border-top:none;border-left:none'
  x:num="83.833333333333343" x:fmla="=B40+0.4*C40+0.5*D40">83.83333333</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>B</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl2423276 style='height:12.75pt;border-top:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl2423276 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=137 style='width:103pt'></td>
  <td width=103 style='width:77pt'></td>
  <td width=90 style='width:68pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=88 style='width:66pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>
</html>


